# Asal ve Bileşik Sayılar

74. Her çift $n > 6$ tam sayısı için $(n - p, n - q) = 1$ olacak şekilde $p$ ve $q$ asal sayılarının bulunduğunu kanıtlayınız.

75. Hem iki asal sayının toplamı hem de farkı şeklinde yazılabilen tüm asal sayıları bulunuz.

76. $n$ ile $n + 10$ arasında hiçbir asal sayı olmayacak şekilde üç en küçük $n$ pozitif tam sayısını bulunuz. $10m$ ile $10(m + 1)$ arasında hiçbir asal sayı olmayacak şekilde üç en küçük $m$ pozitif tam sayısını bulunuz.

77. $4k + 1$ şeklinde olan her asal sayının, kenar uzunlukları tam sayılar olan bir dik üçgenin hipotenüzünün uzunluğuna eşit olduğunu kanıtlayınız.

78. $p, q, r$ asal sayılar olmak üzere, $p^2 + 1 = q^2 + r^2$ denkleminin tüm çözümünü bulunuz.

79. $p, q, r, s, t$ asal sayılar olmak üzere $p^2 + q^2 = r^2 + s^2 + t^2$ denkleminin çözümünün bulunmadığını kanıtlayınız.

80. $(p + 1) + q(q + 1) = r(r + 1)$ denkleminin tüm $p, q, r$ asal çözümlerini bulunuz.

81. $p(p + 1), q(q + 1), r(r + 1)$ sayılarının bir artan aritmetik dizi oluşturmasını sağlayan tüm $p, q, r$ asal sayılarını bulunuz.

82. $n + 1, n + 3, n + 7, n + 9, n + 13$ ve $n + 15$ sayılarının her birinin asal olmasını sağlayan tüm $n$ pozitif tam sayılarını bulunuz.

83. İki tam sayının dördüncü dereceden kuvvetinin toplamına eşit olan beş asal sayıyı bulunuz.

84. İkiz asal sayılar olmayan sonsuz sayıda ardışık asal sayılar çiftinin bulunduğunu kanıtlayınız.

85. Hiçbir ikiz asal sayıda bulunmayan sonsuz tane asal sayı bulunduğunu kanıtlayınız.

86. $n^2 - 1$ sayısının birbirinden farklı üç asal sayının çarpımına eşit olmasını sağlayan en küçük beş $n$ pozitif sayısını bulunuz.

87. $n^2 + 1$ sayısının birbirinden farklı üç asal sayının çarpımına eşit olmasını sağlayan en küçük beş $n$ pozitif sayısını bulunuz. $n^2 + 1$ sayısının birbirinden farklı üç tek sayının çarpımına eşit olmasını sağlayan bir $n$ pozitif sayısı bulunuz.

88. 7’den büyük olan her ardışık üç sayının en az birinin en az iki birbirinden farklı asal böleninin bulunduğunu kanıtlayınız.

89. $n, n + 1, n + 2$ sayılarından her biri birbirinden farklı iki asal sayının çarpımına eşit olacak şekilde beş en küçük pozitif tam sayıyı bulunuz. Bu özellikle sahip olan dört ardışık sayı dizisini bulunmadığını kanıtlayınız. Her birinin tam iki asal böleni bulunan dört ardışık pozitif tam sayıyı bulunuz.

90. Aşağıdaki teoremlerin birbirine denk olduğunu gösteriniz:

   (a) $n$ ve $n + 1$ sayılarının her birinin sadece bir asal böleni olmasını sağlayan $n$ pozitif tam sayıları sonlu sayıdadır.

   (b) Sadece sonlu sayıda Mersenne asal sayıları ve sonlu sayıda Fermat asal sayıları vardır.

91. $n$ pozitif tam sayı olmak üzere milyonlarca büyük olmayan ve iki asal sayının çarpımına eşit olan tüm $2^n - 1$ şeklinde olan sayıları bulunuz. Eğer $n$ çift ise ya da $n > 4$'ten büyükse, $2^n - 1$ sayısının 1’den büyük en az üç asal sayının çarpımı şeklinde gösterilebileceğini kanıtlayınız.

92.  Problem 47'yi kullanarak, $p_n$, $n$. asal sayıyı göstermek üzere,her $n \geq 3$ için $p_{n+1} + p_{n+2} \leq p_1 \cdot p_2 \cdot \cdots \cdot p_n$ eşitsizliğinin doğru olduğunu kanıtlayınız.

93. $n$ pozitif tam sayısı için $q_n$ ile, $n$'nin böleni olmayan en küçük asal sayıyı gösterelim. 92. problemi kullanarak $\lim_{n \to \infty} \frac{q_n}{n} = 0$ olduğunu kanıtlayınız.

94. Her $n > 4$ tam sayısı için $n$ ile $2n$ arasında birbirinden farklı iki asal sayının çarpımına eşit olan en az bir tam sayının bulunduğunu ve her $n > 15$ tam sayısı için $n$ ile $2n$ arasında, birbirinden farklı üç asal sayının çarpımına eşit olan en az bir sayı bulunduğunu kanıtlayınız.

95. Her $s$ pozitif tam sayısı için, yeterince büyük $n$'ler için $n$ ile $2n$ arasında $s$ tane birbirinden farklı asal sayının çarpımına eşit olan en az bir sayı bulunduğunu kanıtlayınız.

96. $1, 31, 331, 3331, \dots$ sonsuz dizisinde sonsuz sayıda bileşik sayı bulunduğunu kanıtlayınız ve bunlardan en küçüğünü bulunuz.

97. $n^4 + (n + 1)^4$ sayısının bileşik olmasını sağlayan en küçük $n$ pozitif tam sayısını bulunuz.

98. $10^n + 3$ $(n = 1, 2, 3, \dots)$ şeklinde olan sonsuz sayıda bileşik sayı bulunduğunu kanıtlayınız.

99. $n > 1$ tam sayıları için $\dfrac{2^{4n+2} + 1}{5}$ sayısının bileşik olduğunu kanıtlayınız.

100. Her $m$ pozitif tam sayısı için $2^n - 1$ $(n = 1, 2, 3, \dots)$ sonsuz dizisinin, bileşik sayılardan oluşan $m$ ardışık teriminin bulunduğunu kanıtlayınız.

101. Bir basamağı değiştirilerek bir asal sayı elde edilemeyen bir pozitif tam sayı bulunduğunu gösteriniz.

102. Aşağıdaki teoremlerin birbirine denk olduğunu kanıtlayınız:

(a) **T.** Her $n > 1$ tam sayısı için $n$ ile $2n$ arasında en az bir asal sayı bulunur.

(b) **T1.** Her $n > 1$ tam sayısı için $n!$ sayısının asal çarpanlarına ayrılışında üstü bir olan en az bir asal sayı bulunur.

103. Her $n$ pozitif tam sayısı için $n!$ sayısının asal çarpanlarına ayrımında kuvveti 1 olan en az iki asal sayı bulunur.

104. Her $n$ pozitif tam sayısı için, $p - 1$ ve $p + 1$ sayılarının her birinin en az $n$ tane pozitif tam böleni olacak şekilde bir $p$ asal sayısı bulunduğunu kanıtlayınız.

105. $p - 1$ ve $p + 1$ sayılarından her birinin en az 3 farklı asal böleni bulunacak şekilde en küçük $p$ asal sayısını bulunuz.

106. Her $n$ pozitif tam sayısı için, $p - 1$, $p + 1$ ve $p + 1$ sayılarının her birinin en az $n$ tane farklı asal böleni olacak şekilde sonsuz sayıda $p$ asal sayısının bulunduğunu kanıtlayınız.

107. Her $n$ ve $s$ pozitif tam sayıları için, her biri terimlerinin en az $n$ farklı asal böleni olacak ve bu asal sayılardan her birinin kuvveti en az $s$ olacak şekilde istenilen uzunlukta ardışık sayılar dizisinin bulunduğunu kanıtlayınız.

108. $n > 1$ tek sayısı için $n$ ve $n + 2$ sayılarının sayılarının asal olması için, $(n - 1)!$ sayısının $n$ ve $n + 2$ sayılarıyla bölünmemesinin gerek ve yeterli olduğunu kanıtlayınız.

109. Her $m$ pozitif tam sayısı için basamakları toplamı 10’dan büyük olan bir asal sayı bulunduğunu kanıtlayınız.

110. Her $n$ pozitif tam sayısı için en az $m$ basamağı 0 olan asal sayılar bulunduğunu kanıtlayınız.

111. $p^4$ sayısının tüm pozitif tam bölenlerinin toplamı tam kare olacak şekilde olan tüm asal sayıları bulunuz.

112. $2 \leq s \leq 10$ olmak üzere her $s$ için pozitif tam bölenlerinin toplamı bir tam sayının $s$. dereceden kuvvetine eşit olan asal sayıları bulunuz.


113. $(p - 1)! + 1 = p^m$ denkleminin, $p > 5$ bir asal sayı ve $m$ bir pozitif tam sayı olacak şekilde hiçbir çözümünün bulunmadığını kanıtlayınız.

114. Bir $n < q$ pozitif tam sayısı için $q_n$, $(n - 1)!$ sayısını bölecek şekilde sonsuz sayıda $q$ asal sayısının bulunduğunu kanıtlayınız.

115. Her $k \neq 1$ için, $2^n + k$ sayısı bileşik olacak şekilde sonsuz sayıda $n$ pozitif tam sayı bulunduğunu kanıtlayınız.

116. Tüm $2^n + k$ $(n = 1, 2, 3, \dots)$ sayıları bileşik olacak şekilde sonsuz sayıda $k > 0$ tam sayısının bulunduğunu kanıtlayınız.

117. Her $n = 1, 2, \dots$ sayısı için $2^{2n+1} + 3, 2^{2n+1} + 7, 2^{2n+2} + 13, 2^{2n+1} + 19$ ve $2^{2n+2} + 21$ sayılarının her birinin bileşik olduğunu kanıtlayınız.

118. Tüm $k \cdot 2^n + 1$ $(n = 1, 2, \dots)$ sayıları bileşik olacak şekilde sonsuz sayıda $k$ pozitif tam sayısı bulunduğunu kanıtlayınız.

119. Her $2^n + k$ $(n = 1, 2, \dots)$ sayısı bileşik olacak şekilde sonsuz sayıda $k$ tek sayısının bulunduğunu kanıtlayınız.

120. $k$ sayısı $2$’nin bir kuvveti ise, yeterince büyük $n$ sayıları için tüm $k \cdot 2^n + 1$ sayılarının bileşik olduğunu kanıtlayınız.

121. Her $k \leq 10$ pozitif tam sayısı için $2^n + k$ sayısının bileşik olmasını sağlayan en küçük $n$ pozitif tam sayısını bulunuz.

122. Her $k \cdot 2^n + 1$ $(n = 1, 2, \dots)$ sayısının bileşik olmasını sağlayan tüm $k \leq 10$ pozitif tam sayılarını bulunuz.

123. Her $n > 1$ tam sayısı için $\dfrac{2^{2n+1} + 2^n + 1}{3}$ sayısının bileşik olduğunu kanıtlayınız.

124. $(2^n + 1)^2 + 2^n$ şeklinde olan sonsuz sayıda bileşik sayı bulunduğunu kanıtlayınız.

125. $1 < a \leq 100$ olmak üzere her $a$ tam sayısı için $a^{2^n} + 1$ sayısının bileşik olacak şekilde en az bir $n \leq 6$ pozitif tam sayısının bulunduğunu kanıtlayınız.

126. Üç tane asal sayının toplamı şeklinde gösterilebilen fakat üçten az sayıda asal sayının toplamı şeklinde gösterilemeyen sonsuz sayıda tek sayı bulunduğunu kanıtlayınız.

127. $f(1) = 2, f(2) = 3, f(3) = 5$ eşitliklerini sağlayan ve katsayıları tam sayılar olan hiçbir $f(x)$ polinomunun bulunmadığını ve her $m > 1$ tam sayısı için, $p_n = n$ asal sayılar dizisi türese $(f(k) = p_n (n = 1, 2, \dots))$ olacak şekilde katsayıları rasyonel sayılar olan bir $f(x)$ polinomunun bulunduğunu kanıtlayınız.

128. Her $n$ pozitif tam sayısı için $f(1) < f(2) < \dots < f(n)$ sayıları asal olacak şekilde katsayıları tam sayılar olan bir $f(x)$ polinomu bulunduğunu kanıtlayınız.

129. $x$ değişkeninin $m$ farklı değerinde $m$ farklı asal sayı veren ve katsayıları tam sayılar olan bir indirgenmez $f(x)$ polinomu bulunuz.

130. $f(x)$, derecesi 0’dan büyük olan tam sayı katsayılı bir polinomsal, sonsuz sayıda $p$ asal sayısı için $f(x) = 0 \pmod{p}$ denkleminin çözümünün bulunduğunu kanıtlayınız.

131. $k + 1, k + 2, \dots, k + 10$ dizisi maksimum sayıda asal sayı içerecek şekilde tüm $k \geq 0$ tam sayılarını bulunuz.

132. $k + 1, k + 2, \dots, k + 100$ dizisi maksimum sayıda asal sayı içerecek şekilde tüm $k \geq 0$ tam sayılarını bulunuz.

133. 25 tane asal sayı içeren tüm 100 ardışık sayıdan oluşan dizileri bulunuz.

134. 8 tane asal sayı içeren tüm 21 ardışık sayıdan oluşan dizileri bulunuz.

135. $p, p + 2, p + 6, p + 8, p + 12, p + 14$ sayılarının her biri asal olacak şekilde tüm $p$ asal sayılarını bulunuz.

136. Aşağıdaki koşulları sağlayan sonsuz sayıda bir birinden farklı $m$ ve $n$ pozitif tam sayı ikilisinin bulunduğunu kanıtlayınız:

(a) $m$ ve $n$ sayılarının asal bölenleri aynıdır;

(b) $m + 1$ ve $n + 1$ sayılarının asal bölenleri aynıdır.
