# Diofant Denklemleri

137. $3x^2 - 7y^2 + 1 = 0$ denkleminin pozitif tam sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

138. $2x^3 + xy - 7 = 0$ denkleminin tüm tam sayı çözümlerini bulunuz ve pozitif rasyonel sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

139. $(x - 1)^2 + (x + 1)^2 = y^2 + 1$ denkleminin pozitif tam sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

140. $x(x + 1) = 4y(y + 1)$ denkleminin pozitif tam sayı çözümünün bulunmadığını, fakat pozitif rasyonel sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

141. $p$ bir asal sayı ve $n$ de bir pozitif tam sayı ise, $x(x + 1) = p^n y(y + 1)$ denkleminin pozitif tam sayılarla hiçbir çözümünün bulunmadığını kanıtlayınız.

142. Verilen $k$ tam sayısı için $x^2 - 2y^2 = k$ denkleminin bir $(x_0, y_0)$ tam sayı çözümü varsa, $x^2 - 2y^2 = -k$ denkleminin bir tam sayı çözümünü bulunuz.

143. Her $D$ tam sayısı için $x^2 - Dy^2 = z^2$ denkleminin pozitif tam sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

144. $D$, sıfırdan farklı herhangi tam sayı ise, $x^2 - Dy^2 = z^2$ denkleminin, $\text{OBEB}(x, y) = 1$ olacak şekilde çözümleri olan tam sayılarla sonsuz tane $(x, y, z)$ çözümünün bulunduğunu kanıtlayınız.

145. $xy + x + y = 3z^2$ denkleminin pozitif tam sayılarla çözümlerinin bulunduğunu ve $x \leq y$ koşulunu sağlayan sayılarla çözümlerinin sonlu olduğunu kanıtlayınız.

146. $x^2 - 2y^2 + 8z = 3$ denkleminin pozitif tam sayılarla çözümünün bulunmadığını kanıtlayınız.

147. $y^2 - x(x + 1)(x + 2)(x + 3) = 1$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.


148. $x^2 + y^2 + z^2 + x + y + z = 1$ denkleminin tüm rasyonel sayı çözümlerini bulunuz.

149. $4xy - x - y = z^2$ denkleminin pozitif tam sayı çözümlerinin bulunmadığını ve negatif tam sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

150. $m$ pozitif tam sayı olmak üzere $D = m^2 + 1$ ise, $x^2 + Dy^2 = 1$ denkleminin pozitif tam sayılarla sonsuz tane çözümünün bulunduğunu kanıtlayınız.

151. $y^2 = x^3 + (x + 4)^2$ denkleminin tüm tam sayı çözümlerini bulunuz.

152. Her $m$ pozitif tam sayısı için $\frac{x}{y} + \frac{y}{z} + \frac{z}{x} = m$ denkleminin, $x, y, z$ aralarında asal olmak üzere tüm pozitif tam sayı çözümlerini bulunuz.

153. $\frac{x}{y} + \frac{y}{z} = \frac{z}{x} = 1$ denkleminin pozitif tam sayılarla çözümünün bulunmadığını kanıtlayınız.

154. $\frac{x}{y} + \frac{y}{z} = \frac{z}{x} = 2$ denkleminin pozitif tam sayılarla çözümünün bulunmadığını kanıtlayınız.

155. $x^2 + y^2 + z = 3$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.

156. $m = 1$ ve $m = 2$ için $x^3 + y^3 + z^3 = mxyz$ denkleminin pozitif tam sayılarla çözümünün bulunmadığını kanıtlayınız ve $m = 3$ için tüm pozitif tam sayı çözümlerini bulunuz.

157. Aşağıdaki $(T_1)$ ve $(T_2)$ teoremlerinin denk olduğunu kanıtlayınız:

- $(T_1): \frac{x}{y} + \frac{y}{z} = \frac{z}{x}$ denkleminin pozitif tam sayılarla çözümü yoktur.
- $(T_2): u^3+v^3 = w^3$ denkleminin pozitif tam sayılarla çözümü yoktur.

158. $\frac{x}{y} + \frac{y}{z} + \frac{z}{t} +\frac{t}{x} = 1$ denkleminin pozitif tam sayılarla çözümünün bulunduğunu, fakat sonsuz sayıda tam sayı çözümünün bulunduğunu kanıtlayınız.


159. $\frac{x}{y} + \frac{y}{z} + \frac{z}{t} + \frac{t}{x} = m$ denkleminin, $m = 2$ ve $m = 3$ için pozitif tam sayılarla çözümünün bulunmadığını kanıtlayınız ve $m = 4$ için tüm pozitif tam sayı çözümlerini bulunuz.

160. $\frac{1}{x} + \frac{1}{y} + \frac{1}{z} + \frac{1}{t} = 1$ denkleminin, $x \leq y \leq z \leq t$ olmak üzere tüm pozitif tam çözümlerini bulunuz.

161. Her $s$ pozitif tam sayısı için $\frac{1}{x_1} + \frac{1}{x_2} + \dots + \frac{1}{x_s} = 1$ denkleminin sonlu sayıda pozitif tam sayı çözümünün bulunduğunu kanıtlayınız.

162. Her $s \geq 2$ tam sayısı için $\frac{1}{x_1} + \frac{1}{x_2} + \dots + \frac{1}{x_s} = 1$ denkleminin $x_1 < x_2 < \dots < x_s$ eşitsizliklerini sağlayan bir pozitif tam sayı çözümünün bulunduğunu kanıtlayınız. Bu çözümlerin sayısını $I_n$ ile gösterirsek, $s = 3, 4, \dots$ için $I_{s+1} > I_s$ olduğunu gösteriniz.

163. $s$, 2'den farklı pozitif tam sayı ise, $\frac{1}{x_1} + \frac{1}{x_2} + \dots + \frac{1}{x_s} = 1$ denkleminin üçgen sayıları ile (yani $t_n = \frac{n(n+1)}{2}$ şeklinde olan sayılar) çözümünün bulunduğunu kanıtlayınız.

164. $\frac{1}{x_1} + \frac{1}{y^2} + \frac{1}{z^2} + \frac{1}{t^2} = 1$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.

165. $\frac{1}{x_1} + \frac{1}{x_2} + \dots + \frac{1}{x_s} = 1$ denkleminin en az bir pozitif tam sayı çözümünün bulunmasını sağlayan tüm $s$ pozitif tam sayılarını bulunuz.

166. $1^2$ sayısının sonlu sayıda artan pozitif tam sayının karelerinin terslerinin toplamı şeklinde gösteriniz.

167. Her $m$ pozitif tam sayısı ve tüm yeterince büyük $s$ pozitif tam sayıları için $\frac{1}{x_1^m} + \frac{1}{x_2^m} + \dots + \frac{1}{x_s^m} = 1$ denkleminin en az bir pozitif tam sayı çözümünün bulunduğunu kanıtlayınız.

168. Her $s$ pozitif tam sayısı için
$$\frac{1}{x_1^2} + \frac{1}{x_2^2} + \dots + \frac{1}{x_s^2} = \frac{1}{x_{s+1}^2}$$ 
denkleminin sonsuz sayıda pozitif tam sayı çözümünün bulunduğunu kanıtlayınız.

169. Her $s \geq 3$ pozitif tam sayısı için
$$\frac{1}{x_1^3} + \frac{1}{x_2^3} + \dots + \frac{1}{x_s^3} = \frac{1}{x_{s+1}^3}$$ 
denkleminin sonsuz sayıda pozitif tam sayı çözümünün bulunduğunu kanıtlayınız.

170. $x + y + z = 3$ ve $x^3 + y^3 + z^3 = 3$ denklemler sisteminin tüm tam sayı çözümlerini bulunuz.

171. Hangi $n$ pozitif tam sayıları için $3x + 5y = n$ denkleminin en az bir tane pozitif tam sayı çözümü bulunduğunu araştırın ve $n$ sonsuzluğa gittiğinde bu çözüm sayısının da sonsuzluğa gittiğini kanıtlayınız.

172. $n^x + n^y = n^z$ denkleminin tüm $n, x, y, z$ pozitif tam sayı çözümlerini bulunuz.

173. Her $(m,n)$ pozitif tam sayı ikilisi için tek bir $x = n, x = m$ pozitif tam sayı çözümü olan, $a, b, c$ tam sayılar olmak üzere bir $ax + by = c$ denkleminin bulunduğunu kanıtlayınız.

174. Her $m$ pozitif tam sayısı için tam $m$ tane pozitif tam sayı çözümü olan, $a, b, c$ tam sayılar olmak üzere bir $ax + by = c$ denkleminin bulunduğunu kanıtlayınız.

175. $m$ verilen bir pozitif tam sayı olmak üzere 
$$x^2 + y^2 + 2xy - mx - my - m - 1 = 0$$ 
denkleminin tam $m$ tane pozitif tam sayı çözümünün bulunduğunu kanıtlayınız.

176. $x^3 + (x + 1)^3 + (x + 2)^3 = (x + 3)^3$ denkleminin tüm tam sayı çözümlerini bulunuz.

177. Her $n$ pozitif tam sayısı için
$$ (x + 1)^3 + (x + 2)^3 + \dots + (x + n)^3 = y^3 $$ 
denkleminin tam sayı çözümünün bulunduğunu kanıtlayınız.

178. $(x + 1)^3 + (x + 2)^3 + (x + 3)^3 + (x + 4)^3 = (x + 5)^3$ denkleminin tüm tam sayı çözümlerini bulunuz.

179. $(x + 1)^3 + (x + 2)^3 + (x + 3)^3 + (x + 4)^3 = (x + 10)^3$ denkleminin tüm tam sayı çözümlerini bulunuz.

180. $y(y + 1) = x(x + 1)(x + 2)$ denkleminin iki tane pozitif tam sayı çözümünü bulunuz.

181. $1 + x^2 + y^2 = z^2$ denkleminin sonsuz sayıda pozitif tam sayı çözümünün bulunduğunu kanıtlayınız.

182. $n, x, y, z, t$ pozitif tam sayılar olmak üzere $nx^2 + ny^2 + nz^2 = nt$ denkleminin tüm çözümlerini bulunuz.

183. $x, y, z, t$ pozitif tam sayılar olmak üzere $4x + 4y + 4z = 4t$ denkleminin tüm çözümlerini bulunuz.

184. $2^m - 3^n = 1$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.

185. $3^n - 2^m = 1$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.

186. $2x + 1 = y^2$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.

187. $2x + 1 = y^2$ denkleminin tüm pozitif tam sayı çözümlerini bulunuz.

188. $x^2 + 2y^2 = z^2, 2x^2 + y^2 = t^2$ denklemler sisteminin $x, y, z, t$ pozitif tam sayılar olmak üzere çözümünün bulunmadığını kanıtlayınız.


189. $[2(3x + 2y + 1) + 1]^2 - 2(4x + 3y + 2)^2 = (2x + 1)^2 - 2y^2$ özdeşliğini kullanarak $x^2 + (x + 1)^2 = y^2$ denkleminin sonsuz sayıda pozitif tam sayı kökünün bulunmadığını kanıtlayınız.

190. $[2(7y + 12x + 6)]^2 - 3[2(4y + 7x + 3) + 1]^2 = (2y)^2 - 3(2x + 1)^2$ özdeşliğini kullanarak $(x + 1)^3 - x^3 = y^2$ denkleminin sonsuz sayıda pozitif tam sayı kökünün bulunmadığını kanıtlayınız.

191. $x^2 + 5y^2 = z^2$ ve $5x^2 + y^2 = t^2$ denklemler sisteminin $x, y, z, t$ pozitif tam sayılarıyla çözümünün bulunmadığını kanıtlayınız.

192. Problem 34'ü kullanarak $x^2 + 6y^2 = z^2$ ve $6x^2 + y^2 = t^2$ denklemler sisteminin $x, y, z, t$ pozitif tam sayılarıyla çözümünün bulunmadığını kanıtlayınız.
    
a. $x^2 + 7y^2 = z^2$ ve $7x^2 + y^2 = t^2$ denklemler         sisteminin   $x, y, z, t$ pozitif tam sayılarıyla çözümünün bulunmadığını kanıtlayınız.

193. V.A. Lebesprogue teoremini kullanarak $x^2 - y^3 = 7$ denkleminin $x, y$ tam sayılarıyla çözümünün bulunmadığını kanıtlayınız.

194. $c$ pozitif tam sayısı tekse, $x^2 - y^3 = (2c)^3 - 1$ denkleminin $x, y$ tam sayılarıyla çözümünün bulunmadığını kanıtlayınız.

195. $k$ pozitif tam sayı ise, $x^2 + 2k^2 + 1 = y^3$ denkleminin $x, y$ pozitif tam sayılarıyla çözümünün bulunmadığını kanıtlayınız.

196. $x \leq y, x \leq z \leq t$ olmak üzere $x + y = zt$ ve $z + t = xy$ denklemler sisteminin $x, y, z, t$ pozitif tam sayılarıyla tüm çözümlerinin bulunması ile ilgili A. Moessner problemini çözünüz. Sistemin sonsuz sayıda $x, y, z, t$ tam sayı çözümünün bulunduğunu kanıtlayınız.


197. Her $p$ pozitif tam sayıları için $x_1 + x_2 + \dots + x_n = z_n$ denkleminin $x_1, x_2, \dots, x_n$ pozitif tam sayılarıyla en az bir çözümünün bulunduğunu kanıtlayınız.

198. Verilen her $a$ ve $n$ pozitif tam sayıları için $x^n - y^n = a$ denkleminin $x, y$ pozitif tam sayı çözümlerinin belirlenmesi için yöntem bulunuz.

199. Elementer yöntemlerle, hem üçgen hem de beşgen (yani $\frac{k(3k-1)}{2}$ şeklinde) olan sonsuz sayıda sayı bulunduğunu kanıtlayınız.
